### ISSUE TITLE
Pre-built docker image not supporting arm64 since v1.5.9

### ISSUE THREAD

**Issue by mrtoth** [GoogleCloudPlatform/cloud-spanner-emulator#132]
Since v1.5.9 the docker image doesn't support arm64.

With the following docker-compose.yaml:
```
---
version: "2.4"

services:
  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator:1.5.10
    platform: linux/arm64/v8
    container_name: spanner
    restart: always
    ports:
      - "9010:9010"
      - "9020:9020"
```

You get: 
Error response from daemon: image with reference gcr.io/cloud-spanner-emulator/emulator:1.5.10 was found but does not match the specified platform: wanted linux/arm64/v8, actual: linux/amd64

v1.5.8 works fine.
