### ISSUE TITLE
Version 1.5.13 breaks Github Actions

### ISSUE THREAD

**Issue by gvastakis** [GoogleCloudPlatform/cloud-spanner-emulator#152]
Hello, 

After updating to [version 1.5.13](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases/tag/v1.5.13) a Github Action responsible for my CI pipeline (that creates an emulator for integration tests) fails with the following error.

`ERROR: gcloud crashed (ConnectionError): HTTPConnectionPool(host='localhost', port=9020): Max retries exceeded with url: /v1/projects/emulator-project/instances?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f036b291ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

It seems the new version has some issue with specifying the ports ? Bellow is the related part of my ci.yml

```
    ..........
    services:
      emulator:
        image: gcr.io/cloud-spanner-emulator/emulator:1.5.12
        ports:
          - 9010:9010
          - 9020:9020
```

Before (v.1.5.12)

<img width="1383" alt="before" src="https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/assets/5776654/36744c44-39c0-471a-b6bf-ed97e327de59">

After (v.1.5.13)

<img width="1370" alt="after" src="https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/assets/5776654/3759979b-fdd3-4445-aa95-5b1e049f4d5d">

Reverting back to v.1.5.12 fixed the issue for me.

Thanks in advance,
Yannos
